name: allChannels.json Updater
on:
 schedule:
   - cron: "00 10  * * *"
 workflow_dispatch:
  inputs:
defaults:
  run:
    shell: bash
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Tata Play IPTV allChannels.json Updater
      run: |
            git config --global user.name "github-actions[bot]"
            git config --global user.email "github-actions[bot]@users.noreply.github.com"
            git clone "https://${{ secrets.GIT_TOKEN }}@github.com/baadshah0786/allChannels-updater.git"
            cd allChannels-updater/code_samples
            python3.8 allChannels.py > /dev/null 2>&1
            # cat allChannel.json | bash <(curl -s 'https://gist.githubusercontent.com/Mobassar4u/6d28dba7588f2e17e376d8c75dea580e/raw/bash-json-parser') | grep 'channel_name' | sed 's/.*channel_name\=//g' | sort > allChannelsName
            sed -i 's/null/\"null\"/g' allChannels.json
            channels=$(cat allChannel.json| grep -0 'channel_genre' | wc -l)
            cd ..
            git add .
            git commit --author="github-actions[bot] <github-actions[bot]@users.noreply.github.com>" -m "Bot: Updated allChannels.json of $channels channels"
            git push            
            exit
