name: allChannels
on:
 schedule:
   - cron: "0 0 */5 * *"
 workflow_dispatch:
  inputs:
defaults:
  run:
    shell: bash
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Tata Play IPTV allChannels.json Updater
      run: |
            git config --global user.name "github-actions[bot]"
            git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git clone "https://${{ secrets.GIT_TOKEN }}@github.com/baadshah0786/All-Channels-Updater.git"
            cd All-Channels-Updater/code_samples
            python allChannels.py > /dev/null 2>&1
            # cat allChannels.json | bash <(curl -s 'https://raw.githubusercontent.com/fkalis/bash-json-parser/master/bash-json-parser') | grep 'channel_name' | sed 's/.*channel_name\=//g' | sort > allChannelsName
            sed -i 's/null/\"null\"/g' allChannels.json
            channels=$(cat allChannels.json| grep -o 'channel_genre' | wc -l)
            cd ..
            git add .
            if [[ -z "$(git log --oneline | head -n1| grep 'Bot: Updated allChannels.json')" ]]; then
              git commit --author="github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>" -m "Bot: Updated allChannels.json of $channels channels"
              git push
            else
               git commit --amend --author="github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>" -m "Bot: Updated allChannels.json of $channels channels"
               git push -f
            fi
            exit
